name: Build and Test to Github Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core 
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.7
        - name: Build with dotnet
          run: dotnet build
        - name: Test
          run: dotnet test
